### ISSUE TITLE
Multi tab...App crashes when creating 20+ tabs

### ISSUE THREAD

**Issue by Imdavyking** [pichillilorenzo/flutter_inappwebview_examples#2]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
|----------------------| ------------- |
| Project Example Name |               |
| Flutter version      |           3.3.3    | 
| Plugin version       |             beta...6.0.21  | 
| Android version      |            11   | 11
| iOS version          |               |
| macOS version        |               |
| Xcode version        |               |

Device information:  google emulator 

## Description

**Expected behavior:** 
App should create tabs as normal without lagging or crashing
**Current behavior:** 
App lags then crash when creating a lot of tabs

## Steps to reproduce

1. This
2. Than that
3. Then

## Stacktrace/Logcat

**Comment by pichillilorenzo** [comment]
post logs if any, also try it in a real device in profile mode

**Comment by Imdavyking** [comment]
I found out it is the emulator storage capacity...
